version: '3.5'

services:
  # |-|-| web_server container |-|-|
  web_server:
    container_name: web_server
    image: saderi/lemmpn
    volumes:
      - ${YOUR_PROJECT_PATH:-./html}:/var/www/html
    environment:
      - WEBROOT=/var/www/html
    ports:
      - '80:80'
    networks:
      - my-stack-network
    restart: always

  ################################
  # |-|-| Database container |-|-|
  ################################

  # |-|-| mysql container |-|-|
  mysql_server:
    container_name: mysql_server
    image: mariadb:${MARIADB_VERSION:-10.2.21}
    hostname: mariadbdev
    networks:
      - my-stack-network
    volumes:
      - ${MYSQL_DATA_PATH:-mysql}:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
    restart: always

  # |-|-| phpMyAdmin container |-|-|
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - ${PHPMYADMIN_ACCESS_PORT:-8086}:80
    networks:
      - my-stack-network
    restart: always
  
  # |-|-| mongoDB container |-|-|
  mongo_db:
    container_name: mongo_db
    image: mongo:${MONGO_VERSION:-4.1.6}
    volumes:
      - ${MONGOBD_DATA_PATH:-mongodb}:/data/db
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-admin123}
    command: mongod --auth
    networks:
      - my-stack-network
    restart: always

networks:
  my-stack-network:
   name: ${NETWORK_NAME:-my-stack-network}

volumes:
    mysql:
    mongodb:
